# Generated by Django 4.1.6 on 2023-02-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Salesmen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salesmen', to='testapp.salesman'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='testapp.customer'),
        ),
    ]
